name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: ${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Coverage
          - build_type: Release

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: "0"

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install libudev-dev

      - name: Configure and build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja -S . -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build -j

      - name: Test
        run: ctest --test-dir build -j

      - name: Check test coverage
        if: ${{ matrix.build_type == 'Coverage' }}
        uses: threeal/gcovr-action@v1.2.0
        with:
          fail-under-line: 70
          fail-under-branch: 70
          fail-under-function: 70
          decisions: true
          fail-under-decision: 70
